### PR TITLE
Use implicit coders instead of CoderRegistry

### PR DESCRIPTION
**Pull request by bcasey-zd**
Instead of passing an implicit TypeTag, then creating a TypeDescriptor, then looking this up in a CoderRegistry, then generating a Coder, just have implicit Coder.

A lot of code goes away and it makes it easier for us to support generic classes. The drawback is that users of our library always have to use our methods (to ensure the coder is passed correctly) but having combed through the codebase it looks like we can make it work.

#### Details
* Replace PipelineOps & TypeTagOps with CoderOps
* Use delegate coder for Scala collections
* Remove static methods from coders - these are only needed by CoderRegistry

#### Risks

* [high] - It's a complete replacement for the CoderRegistry, so we'll need to test carefully. Construct is a good guinea pig for this, as it's a reasonably complex flow.

@zendesk/zodiac

### CODE REVIEW

**Comment by dasch** [comment]
@bcasey-zd this hack is working: https://github.com/zendesk/scala-flow/pull/10/files#diff-ab760eb0462134574d8aed2e6a2077ed

**Comment by dasch** [comment]
After much digging around, I think the best approach is to shield users from having to work with KeyedPCollectionTuple and CoGbkResult at all, as these are not statically typed and therefore break our ability to statically guarantee that a coder is available.

I've pushed an example of that in the form of `coGroupBykey`, a function that returns an actual Scala tuple. We'd need to generate versions for all tuple sizes, of course.

I think this is the best course of action. It allows us to maintain the guarantees we want to make.

**Comment by dasch** [comment]
Similarly, when splitting a stream into multiple output streams, we should use real Scala tuples. I'm not sure exactly how best to let users decide on the routing, though. Maybe something like this?

```scala
val peopleByAgeGroup = people.partition(10, person => person.age / 10)

// Ages 0-9
peopleByAgeGroup._1.writeTo(...)

// Ages 10-19
peopleByAgeGroup._2.writeTo(...)
```

What concrete use cases do we have for splitting collections into more than two?

**Comment by bcasey-zd** [comment]
Shielding the user is not the direction I want to take at the moment. Unless we wrap everything, then it leaves traps that the unwary can fall into. Plus it defeats the purpose of this library which is to be close to the Dataflow/Beam API.

Let's back up for a second and review the problem we're trying to solve:
Easily creating coders for parameterised types e.g. Foo[T].

The implicits coders solve this nicely but come with some baggage (as above)
I've been giving this some thought and a macro based solution for parameterised classes should be feasible - this would give us the best of both worlds, easy coders but also full compatibility with the Dataflow API.

**Comment by dasch** [comment]
I'm not so sure – the more I work on this, the more it makes sense to make the API natural to Scala. That includes using real tuples rather than Dataflow's weird TupleTag system. I think the API produced by this direction is superior to the alternative.

**Comment by dasch** [comment]
For instance: the `coGroupByKey` function is vastly simpler (and I think better) than the original pure Dataflow version.

**Comment by dasch** [comment]
Also: users are free to mess with the "raw" Dataflow API, they just need to end up with a PCollection with an element type that has an implicit coder before we can provide the nice DSL functions.

**Comment by bcasey-zd** [comment]
Adding alternatives that work better is fine as long as we don't break the existing stuff.

However any loopholes and exceptions makes for a bad user experience e.g don't use CoGrpKey with Scala types, don't use apply unless the output type is specified...

**Comment by dasch** [comment]
I think it's fine for now to either have an explicit point of entry (i.e. wrapping PCollection explicitly) or simply state that the DSL methods are only available for types that have a Coder. We can work to improve the experience once we get better at this. In the meantime, implicit coders makes it a lot easier for everybody to write their jobs.

**Comment by dasch** [comment]
@bcasey-zd I think it's a good idea to try an alternative approach as well, but until then we're sort of blocked :-(

**Comment by bcasey-zd** [comment]
Ok, let's roll the dice - I've had enough Coder shenanigans to last a lifetime!

**Comment by dasch** [comment]
I know the feeling...

**Comment by dasch** [comment]
Want me to clean up my commits and force push? I think we should keep 'coGroupByKey' because it's awesome. I'll fix up the test.

**Comment by dasch** [comment]
🎉

**Pull request merged**
